name: Auto Deploy from Main

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  actions: write

jobs:
  auto-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          # Use default token - if this doesn't trigger workflows, we'll need PAT
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create or switch to deploy branch
        run: |
          git fetch origin deploy:deploy 2>/dev/null || git checkout -b deploy
          git checkout deploy

      - name: Reset deploy branch to main
        run: |
          git reset --hard origin/main

      - name: Push to deploy branch
        run: |
          git push --force-with-lease origin deploy

      - name: Create deployment notification
        run: |
          echo "✅ Main branch changes have been merged to deploy branch"
          echo "🚀 Automatic deployment will trigger shortly"
          echo "📱 Live URL: https://CDS-AGENT.github.io/cds-agent-ui/"
